import Head from 'next/head'
import ArticleList from '../components/ArticleList'
import styles from '../styles/Layout.module.css'
import {server} from "../config"

export default function Home({articles}:{articles: {[key:string]: any}[]}) {

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ArticleList articles={articles} />
      
    </div>
  )
}

export const getStaticProps = async()=>{
  const res = await fetch(`${server}/api/articles`)
  const articles = await res.json()

  return{
    props:{
      articles
    }
  }
}