import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Layout.module.css'

export default function Home({articles}:{articles: {[key:string]: any}[]}) {

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {
        articles.map((article)=>(
          <h3 key={article.id}>{article.title}</h3>
        ))
      }
      
    </div>
  )
}

export const getStaticProps = async()=>{
  const res = await fetch("https://jsonplaceholder.typicode.com/posts?_limit=6")
  const articles = await res.json()

  return{
    props:{
      articles
    }
  }
}